source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://git.yingzhongtong.com/digteam/iOS-pods-spec.git' #小赢私有库
platform :ios, '7.0'

target 'AFNetworkingMemoryTest' do
pod 'AFNetworking',     '3.1.0'
end

